version: '3'

services: 
  backend:
    build: ./docker/php
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www

  web_server: 
    image: nginx:1.14
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  database:
    image: mysql:8.0.13
    restart: always
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_RANDOM_ROOT_PASSWORD: root
    networks:
      default:
         aliases:
          - internal_default_bridge
      external_bridge:
        ipv4_address: 172.16.1.101
    ports:
      - 3306
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./docker/mysql/additional-mysql.cnf:/etc/mysql/conf.d/additional-mysql.cnf
      
  database_test:
    image: mysql:8.0.13
    restart: always
    environment:
      MYSQL_DATABASE: default_test
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_RANDOM_ROOT_PASSWORD: root
    networks:
      default:
         aliases:
          - internal_default_bridge
      external_bridge:
        ipv4_address: 172.16.1.102
    ports:
      - 3306
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./docker/mysql/additional-mysql.cnf:/etc/mysql/conf.d/additional-mysql.cnf

  cache:
    image: redis:5.0
    restart: always
    ports:
      - 6379
    volumes:
      - cache_volume:/data

volumes:
  cache_volume:

networks:
  external_bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
